server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: system2
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs2
      __path__: /var/log/*/*log

- job_name: promtail_debug
  static_configs:
  - targets:
      - localhost
    labels:
      job: promtail_debug
      __path__: /opt/*/*.{log,txt}

- job_name: logging
  static_configs:
  - targets:
      - localhost
    labels:
      job: logging
      __path__: /var/log/{messages,firewalld,cron} 

- job_name: bamboo_system_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: bamboo_system_logs
      __path__: /opt/bamboo/atlassian/bamboo/atlassian-bamboo-7.1.2/logs/catalina.out

- job_name: Bamboo build logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: bamboo_build_logs
      __path__: /opt/bamboo/bamboo-home/xml-data/builds/*/download-data/build_logs/*log 
